return {
  misc = {
    dots = '󰇘',
    ellipsis = '…',
    search = '',
    vertical_bar = '│',
    spinner = '󱥸 ',
    dot = '·',
    connected = ' 󰌘 ',
    lines = ' ',
  },
  -- diagnostics = {
  --   Error = '',
  --   Warn = '',
  --   Hint = '',
  --   Info = '',
  -- },
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  separators = {
    triangle_lower_left = '',
    triangle_lower_right = '',
    triangle_upper_left = '',
    triangle_upper_right = '',
    powerline_left = '',
    powerline_right = '',
    circle_left = '',
    circle_right = '',
    block = '▊',
  },
  arrows = {
    right = '',
    down = '',
  },
  git = {
    branch = '',
    added = ' ',
    modified = ' ',
    removed = ' ',
  },
}
