return {
	misc = {
		dots = "󰇘",
		ellipsis = "…",
		search = "",
		vertical_bar = "│",
		spinner = "󱥸 ",
		dot = "·",
		connected = " 󰌘 ",
		lines = " ",
	},
	diagnostics = {
		Error = " ",
		Warn = " ",
		Hint = " ",
		Info = " ",
		ERROR = " ",
		WARN = " ",
		HINT = " ",
		INFO = " ",
		--- 󰔶
	},
	separators = {
		triangle_lower_left = "",
		triangle_lower_right = "",
		triangle_upper_left = "",
		triangle_upper_right = "",
		powerline_left = "",
		powerline_right = "",
		circle_left = "",
		circle_right = "",
		block = "▊",
	},
	arrows = {
		right = "",
		left = "",
		up = "",
		down = "",
	},
	git = {
		branch = "",
	},
	kinds = {
		Array = " ",
		Boolean = "󰨙 ",
		Class = " ",
		Codeium = "󰘦 ",
		Color = " ",
		Control = " ",
		Collapsed = " ",
		Constant = "󰏿 ",
		Constructor = " ",
		Copilot = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Interface = " ",
		Key = " ",
		Keyword = " ",
		Method = "󰊕 ",
		Module = " ",
		Namespace = "󰦮 ",
		Null = " ",
		Number = "󰎠 ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Snippet = " ",
		String = " ",
		Struct = "󰆼 ",
		TabNine = "󰏚 ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = "󰀫 ",
	},
}
