config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  instignore:
  - '*/.git'
variables:
  git_email: sebastian.schleemilch@posteo.net
actions:
  post:
    batcache: bat cache --build
dotfiles:
  d_git:
    src: config/git
    dst: ~/.config/git
  d_k9s:
    src: config/k9s
    dst: ~/.config/k9s
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_bat:
    src: config/bat
    dst: ~/.config/bat
    actions:
    - batcache
  d_btop:
    src: config/btop
    dst: ~/.config/btop
    upignore:
    - btop.log
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    upignore:
    - fish_variables
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_tofi:
    src: config/tofi
    dst: ~/.config/tofi
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_swaync:
    src: config/swaync
    dst: ~/.config/swaync
  f_face:
    src: config/face.png
    dst: ~/.face.png
  d_wallpaper:
    src: config/wallpaper
    dst: ~/wallpaper
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
profiles:
  cli:
    dotfiles:
    - d_git
    - d_k9s
    - d_nvim
    - d_bat
    - d_btop
    - d_kitty
    - d_fish
    - f_starship.toml
  desos:
    dotfiles:
    - d_wallpaper
    - f_face
    include:
    - cli
  ladon:
    dotfiles:
    - d_wallpaper
    - f_face
    include:
    - cli
  work:
    include:
    - cli
    variables:
      git_email: sebastian.schleemilch@bmw.de
      proxy: 127.0.0.1:3128
