font_size 12

# Tabs
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab

# Window movement
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right


# Tab style
tab_bar_style powerline
tab_powerline_style round

cursor_trail 3

enable_audio_bell no
enabled_layouts grid


{%@@ if profile == "work" @@%}
shell /opt/homebrew/bin/fish
{%@@ endif @@%}

macos_quit_when_last_window_closed yes

# BEGIN_KITTY_THEME
# Rosé Pine Moon
include current-theme.conf
# END_KITTY_THEME

# Tab colors
active_tab_foreground #232136
active_tab_background #9ccfd8
inactive_tab_foreground #908caa
inactive_tab_background #44415a

# Window border
active_border_color #9ccfd8
inactive_border_color #44415a

# BEGIN_KITTY_FONTS
font_family      family="Fira Code"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
