MiniDeps.later(function()
    require('mini.pick').setup({
        window = { config = { border = 'solid' } },
    })
    vim.ui.select = MiniPick.ui_select

    vim.keymap.set('n', '<leader>f', function()
        MiniPick.builtin.files()
    end, { desc = 'Find file' })
    vim.keymap.set('n', '<leader>r', function()
        MiniExtra.pickers.oldfiles({ current_dir = true })
    end, { desc = 'Find recent files' })
    vim.keymap.set('n', '<leader>b', function()
        MiniPick.builtin.buffers({ include_current = false })
    end, { desc = 'Find buffer' })
    vim.keymap.set('n', '<leader>/', function()
        MiniPick.builtin.grep_live()
    end, { desc = 'Grep' })
    vim.keymap.set('n', '<leader>ph', function()
        MiniPick.builtin.help()
    end, { desc = 'Find help page' })
    vim.keymap.set('n', '<leader>pr', function()
        MiniPick.builtin.resume()
    end, { desc = 'Resume last picker' })
    vim.keymap.set('n', '<leader>s', function()
        MiniExtra.pickers.lsp({ scope = 'document_symbol' })
    end, { desc = 'LSP Symbols (buffer)' })
    vim.keymap.set('n', '<leader>S', function()
        MiniExtra.pickers.lsp({ scope = 'workspace_symbol' })
    end, { desc = 'LSP Symbols' })
    vim.keymap.set('n', 'gd', function()
        MiniExtra.pickers.lsp({ scope = 'definition' })
    end, { desc = 'LSP Definition' })
    vim.keymap.set('n', 'grr', function()
        MiniExtra.pickers.lsp({ scope = 'references' })
    end, { desc = 'LSP References' })
    vim.keymap.set('n', '<leader>d', function()
        MiniExtra.pickers.diagnostic({ scope = 'current' })
    end, { desc = 'Diagnostics (buffer)' })
    vim.keymap.set('n', '<leader>D', function()
        MiniExtra.pickers.diagnostic({ scope = 'all' })
    end, { desc = 'Diagnostics' })
    vim.keymap.set('n', '<leader>pk', function()
        MiniExtra.pickers.keymaps()
    end, { desc = 'Keymaps' })
    vim.keymap.set('n', '<leader>pq', function()
        MiniExtra.pickers.list({ scope = 'quickfix' })
    end, { desc = 'Quickfixes' })
    vim.keymap.set('n', '<leader>pc', function()
        MiniExtra.pickers.hl_groups()
    end, { desc = 'Highlights' })
    vim.keymap.set('n', '<leader>pk', function()
        MiniExtra.pickers.keymaps()
    end, { desc = 'Keymaps' })
end)
