MiniDeps.later(function()
    require('mini.pick').setup()
    vim.ui.select = MiniPick.ui_select

    vim.keymap.set('n', '<leader><leader>', function()
        MiniPick.builtin.files()
    end, { desc = 'Find file' })
    vim.keymap.set('n', '<leader>,', function()
        MiniPick.builtin.buffers({ include_current = false })
    end, { desc = 'Find buffer' })
    vim.keymap.set('n', '<leader>/', function()
        MiniPick.builtin.grep_live()
    end, { desc = 'Grep' })
    vim.keymap.set('n', '<leader>fr', function()
        MiniExtra.pickers.oldfiles({ current_dir = true })
    end, { desc = 'Find recent file' })
    vim.keymap.set('n', '<leader>fh', function()
        MiniPick.builtin.help()
    end, { desc = 'Find help page' })
    vim.keymap.set('n', '<leader>fs', function()
        MiniExtra.pickers.lsp({ scope = 'document_symbol' })
    end, { desc = 'LSP Symbols' })
    vim.keymap.set('n', 'gd', function()
        MiniExtra.pickers.lsp({ scope = 'definition' })
    end, { desc = 'LSP Definition' })
    vim.keymap.set('n', 'grr', function()
        MiniExtra.pickers.lsp({ scope = 'references' })
    end, { desc = 'LSP References' })
    vim.keymap.set('n', '<leader>fd', function()
        MiniExtra.pickers.diagnostic({ scope = 'current' })
    end, { desc = 'Diagnostics (buffer)' })
    vim.keymap.set('n', '<leader>fD', function()
        MiniExtra.pickers.diagnostic({ scope = 'all' })
    end, { desc = 'Diagnostics' })
    vim.keymap.set('n', '<leader>fk', function()
        MiniExtra.pickers.keymaps()
    end, { desc = 'Keymaps' })
    vim.keymap.set('n', '<leader>fq', function()
        MiniExtra.pickers.list({ scope = 'quickfix' })
    end, { desc = 'Quickfixes' })
    vim.keymap.set('n', '<leader>fc', function()
        MiniExtra.pickers.hl_groups()
    end, { desc = 'Highlights' })
    vim.keymap.set('n', '<leader>fk', function()
        MiniExtra.pickers.keymaps()
    end, { desc = 'Keymaps' })
end)
