return {
    {
        'nvim-treesitter/nvim-treesitter',
        version = false,
        build = ':TSUpdate',
        event = { 'BufReadPre', 'BufNewFile', 'VeryLazy' },
        cmd = { 'TSUpdateSync', 'TSUpdate', 'TSInstall' },
        config = function()
            local configs = require('nvim-treesitter.configs')
            configs.setup({
                ensure_installed = {
                    'bash',
                    'c',
                    'cpp',
                    'css',
                    'csv',
                    'cmake',
                    'diff',
                    'dockerfile',
                    'gitcommit',
                    'go',
                    'graphql',
                    'html',
                    'javascript',
                    'json',
                    'jsonc',
                    'lua',
                    'luadoc',
                    'luap',
                    'markdown',
                    'markdown_inline',
                    'printf',
                    'python',
                    'query',
                    'regex',
                    'toml',
                    'tsx',
                    'typescript',
                    'vim',
                    'vimdoc',
                    'xml',
                    'yaml',
                    'rasi',
                },
                highlight = { enable = true },
                indent = { enable = true },
            })
        end,
    },
    {
        'nvim-treesitter/nvim-treesitter-context',
        opts = {},
    },
}
