MiniDeps.later(function()
    MiniDeps.add('neovim/nvim-lspconfig')
    vim.lsp.enable({
        'lua_ls',
        'basedpyright',
        'ruff',
        'dockerls',
        'gopls',
        'ts_ls',
        'jsonls',
        'yamlls',
        'astro',
        'ltex_plus',
        'buf_ls',
        'marksman',
        'graphql',
    })
end)
