live_config_reload = true

# TOKYONIGHT MOON
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

[colors.cursor]
cursor = '#c8d3f5'
text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

# ROSE-PINE MOON
# [colors.primary]
# foreground = "#e0def4"
# background = "#232136"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"
#
# [colors.cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.search.matches]
# foreground = "#908caa"
# background = "#393552"
#
# [colors.search.focused_match]
# foreground = "#232136"
# background = "#ea9a97"
#
# [colors.hints.start]
# foreground = "#908caa"
# background = "#2a273f"
#
# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#2a273f"
#
# [colors.line_indicator]
# foreground = "None"
# background = "None"
#
# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#2a273f"
#
# [colors.selection]
# text = "#e0def4"
# background = "#44415a"
#
# [colors.normal]
# black = "#393552"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"


# ROSE-PINE
# [colors.primary]
# foreground = "#e0def4"
# background = "#191724"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"
#
# [colors.cursor]
# text = "#e0def4"
# cursor = "#524f67"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#524f67"
#
# [colors.search.matches]
# foreground = "#908caa"
# background = "#26233a"
#
# [colors.search.focused_match]
# foreground = "#191724"
# background = "#ebbcba"
#
# [colors.hints.start]
# foreground = "#908caa"
# background = "#1f1d2e"
#
# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#1f1d2e"
#
# [colors.line_indicator]
# foreground = "None"
# background = "None"
#
# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#1f1d2e"
#
# [colors.selection]
# text = "#e0def4"
# background = "#403d52"
#
# [colors.normal]
# black = "#26233a"
# red = "#eb6f92"
# green = "#31748f"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ebbcba"
# white = "#e0def4"
#
# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#31748f"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ebbcba"
# white = "#e0def4"
#
# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#31748f"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ebbcba"

# CATPPUCCIN MACCHIATO
# [colors.primary]
# background = "#24273a"
# foreground = "#cad3f5"
# dim_foreground = "#8087a2"
# bright_foreground = "#cad3f5"
#
# [colors.cursor]
# text = "#24273a"
# cursor = "#f4dbd6"
#
# [colors.vi_mode_cursor]
# text = "#24273a"
# cursor = "#b7bdf8"
#
# [colors.search.matches]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.search.focused_match]
# foreground = "#24273a"
# background = "#a6da95"
#
# [colors.footer_bar]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.hints.start]
# foreground = "#24273a"
# background = "#eed49f"
#
# [colors.hints.end]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.selection]
# text = "#24273a"
# background = "#f4dbd6"
#
# [colors.normal]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"
#
# [colors.bright]
# black = "#5b6078"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#a5adcb"
#
# [colors.dim]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#f5a97f"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f4dbd6"

# CATPPUCCIN MOCHA
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"


# LACKLUSTER
# [colors.primary]
# background = '#0A0A0A'
#
# [colors.normal]
# # black is gray0
# black = '#080808'
# red = '#D70000'
# green = '#789978'
# yellow = '#ffAA88'
# blue = '#7788AA'
# magenta = '#D7007D'
# # cyan is set to lack
# cyan = '#708090' 
# # white is set to luster
# white = '#DEEEED'

# END OF COLORS

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12

[font.bold]
style = "Bold"
family = "FiraCode Nerd Font"

[font.bold_italic]
style = "Bold Italic"
family = "FiraCode Nerd Font"

[font.italic]
style = "Italic"
family = "FiraCode Nerd Font"

[font.normal]
style = "Regular"
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Control"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 0
y = 0
