format = """
$directory\
[](fg:foam bg:rose)\
$git_branch\
$git_state\
$git_status\
[](fg:rose bg:iris)\
$direnv\
[](fg:iris bg:gold)\
$nodejs\
$golang\
$rust\
$python\
[](fg:gold bg:subtle)\
$jobs\
[](fg:subtle bg:love)\
$status\
[](fg:love bg:base)\
$line_break\
$character\
"""
palette = "rose_pine"

[directory]
format = "[  $path ](bg:foam fg:overlay)"

[direnv]
disabled = false
format = "[ ▼ ](bg:iris fg:overlay)"

[git_branch]
format = "[  $branch ](bg:rose fg:overlay)"

[git_state]
style = "bg:rose fg:overlay"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'

[git_status]
conflicted = "󰉁"
deleted = " "
behind = "󰁅"
ahead = "󰁝"
diverged = " "
format = "[$ahead_behind$all_status ](bg:rose fg:overlay)"
modified = " "
renamed = " "
staged = "󱊽"
stashed = " "
untracked = "󱙀"

[jobs]
format = "[ $symbol$number ](bg:subtle fg:overlay)"
number_threshold = 1
symbol = " "


# Languages
[python]
format = "[ $symbol$pyenv_prefix($version )(($virtualenv)) ](bg:gold fg:overlay)"
symbol = " "

[rust]
format = "[ $symbol($version) ](bg:gold fg:overlay)"
symbol = " "

[golang]
format = "[ $symbol($version)](bg:gold fg:overlay)"
symbol = " "

[nodejs]
format = "[ $symbol($version) ](bg:gold fg:overlay)"
symbol = "󰎙 "

[palettes.rose_pine]
base= "#232136"
surface= "#2a273f"
overlay= "#393552"
muted= "#6e6a86"
subtle= "#908caa"
text= "#e0def4"
love= "#eb6f92"
gold= "#f6c177"
rose= "#ea9a97"
pine= "#3e8fb0"
foam= "#9ccfd8"
iris= "#c4a7e7"

[status]
disabled = false
format = "[  $status](bg:love fg:overlay)"
