format = """
$directory\
$direnv\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill \
$golang\
$nodejs\
$python\
$line_break\
$jobs\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[$path]($style) "

[direnv]
disabled = false
format = "[󰔷]($style) "

[jobs]
format = "[$symbol$number]($style) "
number_threshold = 1
symbol = " "

[git_branch]
format = "[ $symbol$branch]($style) "
symbol = " "

[golang]
format = "[go ($version)]($style) "

[nodejs]
format = "[nodejs ($version)]($style) "

[python]
format = '[py ${pyenv_prefix}(${version} )(\[$virtualenv\] )]($style)'
